local c = {
    bg = "#181818",
    bg_dark = "#101014",
    bg_soft = "#1B1B23",
    bg_panel = "#252531",
    cursorline = "#22232B",

    fg = "#E4E4E4",
    fg_dim = "#D6D2C4",
    muted = "#7F8097",
    comment = "#8A909D",

    selection = "#223249",
    search = "#2D4F67",

    indent = "#25252C",
    indent_scope = "#30303A",

    green = "#A8D86F",
    vcs_green = "#8AC071",
    vcs_red = "#F25A60",
    vcs_yellow = "#F0B862",

    diff_add = "#2B3328",
    diff_delete = "#43242B",
    diff_change = "#252535",
    diff_text = "#49443C",

    error = "#FF514A",
    warn = "#FFB45A",
    info = "#73B8AA",
    hint = "#80AFC6",

    violet = "#B58BF4",
    blue = "#84ADFF",
    blue_soft = "#B5C6F0",
    cyan = "#8AD0E8",
    aqua = "#83D0C0",
    yellow = "#E6BB6D",
    gold = "#FFD47A",
    pink = "#FF92B6",
    red = "#FF7084",
    red_bright = "#FF6D70",
    orange = "#FFB06C",
}

local terminal_colors = {
    c.bg_dark,
    c.vcs_red,
    c.vcs_green,
    c.yellow,
    c.blue,
    c.violet,
    c.info,
    c.fg_dim,
    c.comment,
    c.error,
    c.green,
    c.gold,
    c.cyan,
    c.blue_soft,
    c.aqua,
    c.fg,
    c.orange,
    c.red_bright,
}

local groups = {
    -- Editor
    Normal = { fg = c.fg, bg = c.bg },
    NormalNC = { link = "Normal" },
    Cursor = { fg = c.bg, bg = c.fg },
    lCursor = { link = "Cursor" },
    CursorIM = { link = "Cursor" },
    CursorLine = { bg = c.cursorline },
    CursorColumn = { link = "CursorLine" },
    CursorLineNr = { fg = c.orange, bg = c.bg, bold = true },
    LineNr = { fg = c.muted, bg = c.bg },
    SignColumn = { bg = c.bg },
    FoldColumn = { bg = c.bg },
    ColorColumn = { bg = c.bg_panel },
    WinSeparator = { fg = c.bg_dark, bg = c.bg },
    VertSplit = { link = "WinSeparator" },
    Folded = { fg = c.blue_soft, bg = c.bg_panel },
    EndOfBuffer = { fg = c.bg },
    NonText = { fg = c.muted },
    Whitespace = { fg = c.muted },
    SpecialKey = { fg = c.blue_soft },
    Directory = { fg = c.blue },

    -- Floats and menus
    NormalFloat = { fg = c.fg, bg = c.bg_dark },
    FloatBorder = { fg = c.muted, bg = c.bg_dark },
    FloatTitle = { fg = c.blue_soft, bg = c.bg_dark, bold = true },
    FloatFooter = { fg = c.muted, bg = c.bg_dark },
    Pmenu = { fg = c.fg, bg = c.bg_dark },
    PmenuSel = { fg = c.fg, bg = c.cursorline },
    PmenuKind = { fg = c.fg_dim, bg = c.bg_dark },
    PmenuKindSel = { fg = c.fg_dim, bg = c.cursorline },
    PmenuExtra = { fg = c.blue_soft, bg = c.bg_dark },
    PmenuExtraSel = { fg = c.blue_soft, bg = c.cursorline },
    PmenuSbar = { bg = c.bg_dark },
    PmenuThumb = { bg = c.bg_panel },
    PmenuBorder = { link = "FloatBorder" },

    -- Search and selection
    Visual = { bg = c.selection },
    VisualNOS = { link = "Visual" },
    Search = { fg = c.fg, bg = c.search },
    IncSearch = { fg = "#F2F2F2", bg = c.search },
    CurSearch = { fg = c.fg, bg = c.search, bold = true },
    Substitute = { fg = c.fg, bg = c.vcs_red },
    MatchParen = { fg = c.warn, bold = true },

    -- UI chrome
    StatusLine = { fg = c.fg_dim, bg = c.bg_dark },
    StatusLineNC = { fg = c.muted, bg = c.bg_dark },
    TabLine = { fg = c.blue_soft, bg = c.bg_dark },
    TabLineFill = { bg = c.bg },
    TabLineSel = { fg = c.fg_dim, bg = c.bg_panel },
    WinBar = { fg = c.fg_dim, bg = "NONE" },
    WinBarNC = { fg = c.fg_dim, bg = "NONE" },
    MsgArea = { fg = c.fg_dim },
    MsgSeparator = { fg = c.bg_dark, bg = c.bg_dark },
    ModeMsg = { fg = c.warn, bold = true },
    MoreMsg = { fg = c.info },
    Question = { link = "MoreMsg" },
    ErrorMsg = { fg = c.error },
    WarningMsg = { fg = c.warn },
    QuickFixLine = { bg = c.bg_panel },
    WildMenu = { link = "Pmenu" },

    -- Syntax
    Comment = { fg = c.comment },
    Constant = { fg = c.pink },
    String = { fg = c.green },
    Character = { link = "String" },
    Number = { fg = c.pink },
    Boolean = { link = "Constant" },
    Float = { link = "Number" },
    Identifier = { fg = c.fg },
    Function = { fg = c.blue },
    Statement = { fg = c.violet },
    Conditional = { link = "Statement" },
    Repeat = { link = "Statement" },
    Label = { link = "Statement" },
    Operator = { fg = c.yellow },
    Keyword = { link = "Statement" },
    Exception = { link = "Statement" },
    PreProc = { fg = c.red },
    Include = { link = "PreProc" },
    Define = { link = "PreProc" },
    Macro = { link = "PreProc" },
    PreCondit = { link = "PreProc" },
    Type = { fg = c.aqua },
    StorageClass = { link = "Type" },
    Structure = { link = "Type" },
    Typedef = { link = "Type" },
    Special = { fg = c.cyan },
    SpecialChar = { link = "Special" },
    Tag = { fg = c.red },
    Delimiter = { fg = c.blue_soft },
    SpecialComment = { link = "Comment" },
    Debug = { fg = c.orange },
    Underlined = { fg = c.cyan, underline = true },
    Bold = { bold = true },
    Italic = { italic = true },
    Ignore = { link = "NonText" },
    Error = { fg = c.error },
    Todo = { fg = c.selection, bg = c.info, bold = true },

    -- Diff and diagnostics
    DiffAdd = { bg = c.diff_add },
    DiffDelete = { fg = c.vcs_red, bg = c.diff_delete },
    DiffChange = { bg = c.diff_change },
    DiffText = { bg = c.diff_text },
    diffAdded = { fg = c.vcs_green },
    diffRemoved = { fg = c.vcs_red },
    diffDeleted = { fg = c.vcs_red },
    diffChanged = { fg = c.vcs_yellow },
    diffOldFile = { fg = c.vcs_red },
    diffNewFile = { fg = c.vcs_green },
    DiagnosticError = { fg = c.error },
    DiagnosticWarn = { fg = c.warn },
    DiagnosticInfo = { fg = c.info },
    DiagnosticHint = { fg = c.hint },
    DiagnosticOk = { fg = c.green },
    DiagnosticFloatingError = { link = "DiagnosticError" },
    DiagnosticFloatingWarn = { link = "DiagnosticWarn" },
    DiagnosticFloatingInfo = { link = "DiagnosticInfo" },
    DiagnosticFloatingHint = { link = "DiagnosticHint" },
    DiagnosticFloatingOk = { link = "DiagnosticOk" },
    DiagnosticSignError = { fg = c.error, bg = c.bg },
    DiagnosticSignWarn = { fg = c.warn, bg = c.bg },
    DiagnosticSignInfo = { fg = c.info, bg = c.bg },
    DiagnosticSignHint = { fg = c.hint, bg = c.bg },
    DiagnosticVirtualTextError = { link = "DiagnosticError" },
    DiagnosticVirtualTextWarn = { link = "DiagnosticWarn" },
    DiagnosticVirtualTextInfo = { link = "DiagnosticInfo" },
    DiagnosticVirtualTextHint = { link = "DiagnosticHint" },
    DiagnosticUnderlineError = { undercurl = true, sp = c.error },
    DiagnosticUnderlineWarn = { undercurl = true, sp = c.warn },
    DiagnosticUnderlineInfo = { undercurl = true, sp = c.info },
    DiagnosticUnderlineHint = { undercurl = true, sp = c.hint },

    -- LSP, spell, and filetype defaults
    LspReferenceText = { bg = c.diff_text },
    LspReferenceRead = { link = "LspReferenceText" },
    LspReferenceWrite = { bg = c.diff_text, underline = true },
    LspSignatureActiveParameter = { fg = c.warn },
    LspCodeLens = { fg = c.comment },
    LspInlayHint = { fg = c.comment, bg = c.bg_soft },
    SpellBad = { undercurl = true, sp = c.error },
    SpellCap = { undercurl = true, sp = c.warn },
    SpellLocal = { undercurl = true, sp = c.warn },
    SpellRare = { undercurl = true, sp = c.warn },
    qfLineNr = { link = "LineNr" },
    qfFileName = { link = "Directory" },
    markdownCode = { link = "String" },
    markdownCodeBlock = { link = "String" },
    markdownEscape = {},

    -- Treesitter
    ["@comment"] = { link = "Comment" },
    ["@comment.documentation"] = { link = "Comment" },
    ["@comment.error"] = { fg = c.fg, bg = c.error, bold = true },
    ["@comment.warning"] = { fg = c.selection, bg = c.warn, bold = true },
    ["@comment.note"] = { fg = c.selection, bg = c.hint, bold = true },
    ["@comment.todo"] = { link = "Todo" },
    ["@string"] = { link = "String" },
    ["@string.documentation"] = { link = "String" },
    ["@string.regexp"] = { fg = c.yellow },
    ["@string.escape"] = { fg = c.yellow, bold = true },
    ["@string.special"] = { link = "Special" },
    ["@string.special.symbol"] = { fg = c.gold },
    ["@string.special.url"] = { fg = c.cyan, undercurl = true },
    ["@character"] = { link = "Character" },
    ["@character.special"] = { link = "Special" },
    ["@number"] = { link = "Number" },
    ["@number.float"] = { link = "Float" },
    ["@boolean"] = { link = "Boolean" },
    ["@constant"] = { link = "Constant" },
    ["@constant.builtin"] = { link = "Constant" },
    ["@constant.macro"] = { link = "Macro" },
    ["@variable"] = { link = "Identifier" },
    ["@variable.builtin"] = { fg = c.red, italic = true },
    ["@variable.parameter"] = { fg = c.fg },
    ["@variable.member"] = { link = "@property" },
    ["@parameter"] = { link = "@variable.parameter" },
    ["@field"] = { link = "@property" },
    ["@property"] = { fg = c.gold },
    ["@function"] = { link = "Function" },
    ["@function.call"] = { link = "Function" },
    ["@function.builtin"] = { link = "Special" },
    ["@function.macro"] = { link = "Macro" },
    ["@function.method"] = { link = "Function" },
    ["@function.method.call"] = { link = "Function" },
    ["@method"] = { link = "Function" },
    ["@method.call"] = { link = "Function" },
    ["@constructor"] = { link = "Type" },
    ["@keyword"] = { link = "Keyword" },
    ["@keyword.function"] = { link = "Keyword" },
    ["@keyword.return"] = { link = "Keyword" },
    ["@keyword.operator"] = { link = "Keyword" },
    ["@keyword.import"] = { link = "PreProc" },
    ["@keyword.type"] = { link = "Keyword" },
    ["@keyword.modifier"] = { link = "Keyword" },
    ["@keyword.repeat"] = { link = "Keyword" },
    ["@keyword.exception"] = { link = "Keyword" },
    ["@keyword.conditional"] = { link = "Keyword" },
    ["@conditional"] = { link = "Keyword" },
    ["@repeat"] = { link = "Keyword" },
    ["@operator"] = { link = "Operator" },
    ["@type"] = { link = "Type" },
    ["@type.builtin"] = { fg = c.aqua, italic = true },
    ["@type.definition"] = { link = "Type" },
    ["@module"] = { link = "Type" },
    ["@label"] = { link = "Statement" },
    ["@attribute"] = { link = "Constant" },
    ["@punctuation.delimiter"] = { link = "Delimiter" },
    ["@punctuation.bracket"] = { link = "Delimiter" },
    ["@punctuation.special"] = { link = "Special" },
    ["@markup.strong"] = { bold = true },
    ["@markup.italic"] = { italic = true },
    ["@markup.strikethrough"] = { strikethrough = true },
    ["@markup.underline"] = { underline = true },
    ["@markup.heading"] = { link = "Function" },
    ["@markup.quote"] = { link = "@variable.parameter" },
    ["@markup.math"] = { link = "Constant" },
    ["@markup.environment"] = { link = "Keyword" },
    ["@markup.link.url"] = { link = "@string.special.url" },
    ["@markup.raw"] = { link = "String" },
    ["@diff.plus"] = { fg = c.vcs_green },
    ["@diff.minus"] = { fg = c.vcs_red },
    ["@diff.delta"] = { fg = c.vcs_yellow },
    ["@tag"] = { fg = c.red },
    ["@tag.attribute"] = { fg = c.gold },
    ["@tag.delimiter"] = { link = "Delimiter" },

    -- LSP semantic tokens
    ["@lsp.type.class"] = { link = "Type" },
    ["@lsp.type.decorator"] = { link = "Function" },
    ["@lsp.type.enum"] = { link = "Type" },
    ["@lsp.type.enumMember"] = { link = "Constant" },
    ["@lsp.type.function"] = { link = "Function" },
    ["@lsp.type.interface"] = { link = "Type" },
    ["@lsp.type.macro"] = { link = "Macro" },
    ["@lsp.type.method"] = { link = "@function.method" },
    ["@lsp.type.namespace"] = { link = "@module" },
    ["@lsp.type.parameter"] = { link = "@variable.parameter" },
    ["@lsp.type.property"] = { link = "@property" },
    ["@lsp.type.struct"] = { link = "Structure" },
    ["@lsp.type.type"] = { link = "Type" },
    ["@lsp.type.typeParameter"] = { link = "Typedef" },
    ["@lsp.type.variable"] = { link = "@variable" },
    ["@lsp.type.comment"] = { link = "Comment" },
    ["@lsp.mod.readonly"] = { link = "Constant" },
    ["@lsp.mod.defaultLibrary"] = { link = "Special" },
    ["@lsp.mod.typeHint"] = { link = "Type" },

    -- Current plugins
    BlinkCmpMenu = { link = "Pmenu" },
    BlinkCmpMenuSelection = { link = "PmenuSel" },
    BlinkCmpMenuBorder = { link = "PmenuBorder" },
    BlinkCmpScrollBarThumb = { link = "PmenuThumb" },
    BlinkCmpScrollBarGutter = { link = "PmenuSbar" },
    BlinkCmpLabel = { fg = c.fg },
    BlinkCmpLabelMatch = { fg = c.blue },
    BlinkCmpLabelDetails = { fg = c.comment },
    BlinkCmpLabelDeprecated = { fg = c.comment, strikethrough = true },
    BlinkCmpGhostText = { fg = c.comment },
    BlinkCmpDoc = { link = "NormalFloat" },
    BlinkCmpDocBorder = { link = "FloatBorder" },
    BlinkCmpDocCursorLine = { link = "CursorLine" },
    BlinkCmpSignatureHelp = { link = "NormalFloat" },
    BlinkCmpSignatureHelpBorder = { link = "FloatBorder" },
    BlinkCmpSignatureHelpActiveParameter = { link = "LspSignatureActiveParameter" },
    BlinkCmpKind = { fg = c.fg_dim },
    BlinkCmpKindText = { fg = c.fg },
    BlinkCmpKindMethod = { link = "@function.method" },
    BlinkCmpKindFunction = { link = "Function" },
    BlinkCmpKindConstructor = { link = "@constructor" },
    BlinkCmpKindField = { link = "@property" },
    BlinkCmpKindVariable = { fg = c.fg_dim },
    BlinkCmpKindClass = { link = "Type" },
    BlinkCmpKindInterface = { link = "Type" },
    BlinkCmpKindModule = { link = "@module" },
    BlinkCmpKindProperty = { link = "@property" },
    BlinkCmpKindUnit = { link = "Number" },
    BlinkCmpKindValue = { link = "String" },
    BlinkCmpKindEnum = { link = "Type" },
    BlinkCmpKindKeyword = { link = "Keyword" },
    BlinkCmpKindSnippet = { link = "Special" },
    BlinkCmpKindColor = { link = "Special" },
    BlinkCmpKindFile = { link = "Directory" },
    BlinkCmpKindReference = { link = "Special" },
    BlinkCmpKindFolder = { link = "Directory" },
    BlinkCmpKindEnumMember = { link = "Constant" },
    BlinkCmpKindConstant = { link = "Constant" },
    BlinkCmpKindStruct = { link = "Type" },
    BlinkCmpKindEvent = { link = "Type" },
    BlinkCmpKindOperator = { link = "Operator" },
    BlinkCmpKindTypeParameter = { link = "Type" },
    MiniPickBorder = { link = "FloatBorder" },
    MiniPickBorderBusy = { link = "DiagnosticFloatingWarn" },
    MiniPickBorderText = { link = "FloatTitle" },
    MiniPickIconDirectory = { link = "Directory" },
    MiniPickIconFile = { link = "MiniPickNormal" },
    MiniPickHeader = { link = "DiagnosticFloatingHint" },
    MiniPickMatchCurrent = { link = "CursorLine" },
    MiniPickMatchMarked = { link = "Visual" },
    MiniPickMatchRanges = { link = "DiagnosticFloatingHint" },
    MiniPickNormal = { link = "NormalFloat" },
    MiniPickPreviewLine = { link = "CursorLine" },
    MiniPickPreviewRegion = { link = "IncSearch" },
    MiniPickPrompt = { fg = c.blue, bg = c.bg_dark },
    MiniIconsAzure = { fg = c.cyan },
    MiniIconsBlue = { fg = c.blue },
    MiniIconsCyan = { fg = c.aqua },
    MiniIconsGreen = { fg = c.green },
    MiniIconsGrey = { fg = c.fg },
    MiniIconsOrange = { fg = c.orange },
    MiniIconsPurple = { fg = c.violet },
    MiniIconsRed = { fg = c.red_bright },
    MiniIconsYellow = { fg = c.gold },
    SnacksIndent = { fg = c.indent },
    SnacksIndentScope = { fg = c.indent_scope },

    healthError = { fg = c.error },
    healthSuccess = { fg = c.green },
    healthWarning = { fg = c.warn },
}

vim.o.background = "dark"
vim.o.termguicolors = true

vim.cmd("highlight clear")
if vim.fn.exists("syntax_on") == 1 then
    vim.cmd("syntax reset")
end

vim.g.colors_name = "kanagawa"

for group, spec in pairs(groups) do
    vim.api.nvim_set_hl(0, group, spec)
end

for index, color in ipairs(terminal_colors) do
    vim.g["terminal_color_" .. (index - 1)] = color
end
